### ISSUE TITLE
Media query loses contents.

### ISSUE THREAD

**Issue by back2dos** [back2dos/cix#14]
```haxe
static final NAV_COLUMN = css('
	@media (min-width: 924px) {
		min-height: 100%;
		background: #f00;
	}
');
```

The media query gets generated, but there's no content.

**Comment by markknol** [comment]
Funny, I got the exact same problem!

**Comment by back2dos** [comment]
Hmm, seems to be top level media queries only.

**Comment by back2dos** [comment]
Oh, maybe not even that. Perhaps it was DCE-related? In any case it seems to be working. If not, please provide a minimal example ;)
